name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: temp-sensor-esp32.yaml,temp-sensor-esp8266.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
