name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@multiple-builds
    with:
      files: temp-sensor-esp32.yaml,temp-sensor-esp8266.yaml
      name: Temperature Sensor
